namespace Stats
{
    public enum Stats
    {
        MaxHealth,
        Armor,
        ProjectilesSpeed,
        ProjectilesInterval,
        Area,
        Cooldown,
        Revival,
        Growth,
        Curse,
        Reroll,
        Banish,
        Recovery,
        MoveSpeed,
        Duration,
        Amount,
        Magnet,
        Luck,
        Greed,
        Skip,
        Damage,
        Pierce,
        Chance,
        CriticalHitMultiplier
    }
}